spring:
  application:
    name: todo-app
  datasource:
    url: ${URL_DATABASE_POSTGRESQL:jdbc:postgresql://localhost:5432/todoapp}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9090

app:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-here}
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
  otp:
    length: 6
    expiration-minutes: 5
    max-attempts: 3

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html